MiMailIdentity/Models/CustomerCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MiMailIdentity.Models
{
    public class CustomerCategory : BaseModel
    {
        public string Name { get; set; }

        public virtual ICollection<Customer> GetCustomers { get; set; }
    }
}

MiMailIdentity/Controllers/CustomerCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MiMailIdentity.Models;
using MiMailIdentity.Services.CustomerCategoryRepository;

namespace MiMailIdentity.Controllers
{
    public class CustomerCategoriesController : Controller
    {
        private ICustomerCategoryRepository _repo;
        public CustomerCategoriesController(ICustomerCategoryRepository repository)
        {
            _repo = repository;
        }

        #region Nghiep vu
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult GetById(int id)
        {
            if (id > 0)
            {
                var result = _repo.GetById(id);
                return Ok(result);
            }
            return BadRequest("Not Spectificed category");
        }
        [HttpPost]
        public IActionResult Load(int pageIndex, int pageSize)
        {
            return ViewComponent("ListCustomerCategories", new { pageIndex = pageIndex, pageSize = pageSize });
        }
        [HttpPost]
        public IActionResult Save(CustomerCategory category)
        {
            if (category.Name.Equals("error"))
            {
                return BadRequest("Error Sample");
            }
            if (category != null)
            {
                if (category.Id <= 0)
                {
                    _repo.Insert(category);
                    return Ok("Create Successful!");
                }
                if (category.Id > 0)
                {
                    _repo.Update(category);
                    return Ok("Update Successful!");
                }
            }

            return BadRequest("Not Spectificed category");
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            if (id > 0)
            {
                _repo.Delete(id);
                return Ok("Delete Successful!");
            }
            return BadRequest("Not Spectificed category");
        }
        #endregion

        #region Giao Dien
        [HttpPost]
        public IActionResult GetAddEditModal(int id)
        {
            return ViewComponent("SaveCustomerCategories", new { id = id});
        }
        #endregion

    }
}

MiMailIdentity/ViewComponents/CustomerCategories/ListCustomerCategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiMailIdentity.Services.CustomerCategoryRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Transactions;

namespace MiMailIdentity.ViewComponents.CustomerCategories
{
    public class ListCustomerCategoriesViewComponent : ViewComponent
    {
        private ICustomerCategoryRepository _repository;
        public ListCustomerCategoriesViewComponent(ICustomerCategoryRepository repository)
        {
            _repository = repository;
        }

        public IViewComponentResult Invoke(int CateId, int PageIndex, int PageSize)
        {
            ViewBag.Index = PageIndex;
            ViewBag.Size = PageSize;
            return View();
        }
    }
}

MiMailIdentity/ViewComponents/CustomerCategories/SaveCustomerCategoriesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MiMailIdentity.Services.CustomerCategoryRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MiMailIdentity.ViewComponents.CustomerCategories
{
    public class SaveCustomerCategoriesViewComponent : ViewComponent
    {
        private ICustomerCategoryRepository _repository;
        public SaveCustomerCategoriesViewComponent(ICustomerCategoryRepository repository)
        {
            _repository = repository;
        }

        public IViewComponentResult Invoke(int id)
        {
            ViewBag.Id = id;
            return View();
        }
    }
}

MiMailIdentity/Views/CustomerCategories/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutPublic.cshtml";

}
@{
    var index = 1;
    var size = 10;
}
<section>
    <div class="p-2 border-top">
        <div class="container">
            <div class="giaidoan d-flex">
                <div class="turn-chimuc d-flex active">
                    <div class="nb-turn mr-1 ">1</div>
                    <div>Nhóm khách hàng</div>
                </div>
                <div class="line-turn"></div>
                <a href="/danh-sach-kh/nhom/1" class="turn-chimuc d-flex">
                    <div class="nb-turn mr-1">2</div>
                    <div>List danh sách kH</div>
                </a>
            </div>
        </div>
    </div>
</section>
<section class="main-data-custmer">
    <div class="container">
        <div class="bg-fff">
            <div class="add-group">
                <!-- Button trigger modal -->
                @*<button type="button" class="btn btn-addgr btn-create" data-toggle="modal" data-target="#exampleModal">*@
                <button type="button" class="btn btn-addgr btn-create">
                    <i class="fal fa-plus mr-2"></i> Tạo nhóm mới
                </button>
                <!-- Modal -->
                @*<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">*@
                <div class="modal fade" id="modal-create">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">

                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div id="binding-button">
                </div>

                <div class="table-responsive">
                    <table id="datatable" class="table cust-table">
                        @await Component.InvokeAsync("ListCustomerCategories", new { pageIndex = index, pageSize = size })
                    </table>
                </div>
            </div>
        </div>

        <div id="pagination">

        </div>
        @*<div class="pagin">
                <ul class="number-page bd-top-arts">
                    <li>
                        <a href="#" class="icon-pre">
                            <i class="fal fa-angle-left"></i>
                        </a>
                    </li>
                    <li>
                        <a href="#" title="" class="nb-txt nb-hover active">1</a>
                    </li>
                    <li>
                        <a href="#" title="" class="nb-txt nb-hover">2</a>
                    </li>
                    <li>
                        <a href="#" title="" class="nb-txt nb-hover">3</a>
                    </li>
                    <li>
                        <a title="" class="nb-txt ">...</a>
                    </li>
                    <li>
                        <a href="#" title="" class="nb-txt nb-hover">20</a>
                    </li>
                    <li>
                        <a href="#" class="icon-pre">
                            <i class="fal fa-angle-right"></i>
                        </a>
                    </li>
                </ul>
            </div>*@
    </div>

</section>
@section scripts{
    <script src="~/controllerJs/CustomerCategoriesController.js"></script>
}